### ISSUE TITLE
WP Core Download error "Uncaught exception 'UnexpectedValueException'" ... is a corrupted tar file

### ISSUE THREAD

**Issue by AsaadQ** [wp-cli/wp-cli#1608]
Easyengine (EE) uses WP-CLI and was throwing an error when downloading the wordpress core

```
 wp --allow-root --info
PHP binary:     /usr/bin/php5
PHP version:    5.5.20-1~dotdeb.1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.17.1
```

EE uses this command and throws this:

```
 wp --allow-root core download
```
```
Downloading WordPress 4.1 (en_US)...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'phar error: "/tmp/wp_54b776231cc96.tar.gz" is a corrupted tar file (truncated)' in phar:///usr/bin/wp/php/commands/core.php:181
Stack trace:
#0 phar:///usr/bin/wp/php/commands/core.php(181): PharData->__construct('/tmp/wp_54b7762...')
#1 phar:///usr/bin/wp/php/commands/core.php(167): Core_Command::_extract('/tmp/wp_54b7762...', '/var/www/wpgate...')
#2 [internal function]: Core_Command->download(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(293): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/bin/wp/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_command(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Runn in phar:///usr/bin/wp/php/commands/core.php on line 181
```

I am new w/ WP-CLI so bear with me here

**Comment by danielbachhuber** [comment]
This is probably caused by #1532. Can you try deleting `~/.wp-cli/cache` and see if that fixes it? And you should update WP-CLI if you can to v0.18.0.

**Comment by AsaadQ** [comment]
Trivial question, how do i update wp-cli?

**Comment by danielbachhuber** [comment]
> Trivial question, how do i update wp-cli?

For v0.17.1, the same way you install: http://wp-cli.org/#install

v0.18.0 introduces `wp cli update`, which you'll be able to use going forward.

**Comment by AsaadQ** [comment]
some info:
````
 wp --allow-root --info
PHP binary:     /usr/bin/php5
PHP version:    5.5.20-1~dotdeb.1
php.ini used:   /etc/php5/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 0.18.0

cat /etc/issue
Debian GNU/Linux 7 \n \l

uname -v
#1 SMP Wed Apr 9 22:06:23 UTC 2014

 uname -r
2.6.32-5-vserver-amd64

lsb_release -c
Codename:       wheezy

cat /etc/debian_version
7.8


````

The first time i do
````
wp --allow-root core download
````
i get this:
````
 wp --allow-root core download
Downloading WordPress 4.1 (en_US)...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'phar error: "/tmp/wp_54b7cada132f7.tar.gz" is a corrupted tar file (truncated)' in phar:///usr/bin/wp/php/commands/core.php:190
Stack trace:
#0 phar:///usr/bin/wp/php/commands/core.php(190): PharData->__construct('/tmp/wp_54b7cad...')
#1 phar:///usr/bin/wp/php/commands/core.php(176): Core_Command::_extract('/tmp/wp_54b7cad...', '/var/www/wpgate...')
#2 [internal function]: Core_Command->download(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(295): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/bin/wp/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_command(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Runn in phar:///usr/bin/wp/php/commands/core.php on line 190
````

2nd or 3rd time i run the function, i get this:
````
 wp --allow-root core download
Downloading WordPress 4.1 (en_US)...
Warning: cURL error 23: Failed writing body (364 != 4096)
Error: cURL error 23: Failed writing body (364 != 4096)
````
and once more
````
 wp --allow-root core download
Warning: cURL error 77: error setting certificate verify locations:
  CAfile: /tmp/wp-cli-cacert.pem
  CApath: /etc/ssl/certs

Downloading WordPress 4.1 (en_US)...
Warning: cURL error 77: error setting certificate verify locations:
  CAfile: /tmp/wp-cli-cacert.pem
  CApath: /etc/ssl/certs

Error: cURL error 23: Failed writing body (364 != 4096)
````

to get back to the 1st error i above i delete all the tar.gz files in the /tmp directory, then it goes back to this:

````
wp --allow-root core download
Downloading WordPress 4.1 (en_US)...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'phar error: "/tmp/wp_54b7cba0eeff2.tar.gz" is a corrupted tar file (truncated)' in phar:///usr/bin/wp/php/commands/core.php:190
Stack trace:
#0 phar:///usr/bin/wp/php/commands/core.php(190): PharData->__construct('/tmp/wp_54b7cba...')
#1 phar:///usr/bin/wp/php/commands/core.php(176): Core_Command::_extract('/tmp/wp_54b7cba...', '/var/www/wpgate...')
#2 [internal function]: Core_Command->download(Array, Array)
#3 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(52): call_user_func(Array, Array, Array)
#4 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#5 phar:///usr/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(295): call_user_func(Object(Closure), Array, Array)
#6 phar:///usr/bin/wp/php/WP_CLI/Runner.php(304): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#7 phar:///usr/bin/wp/php/WP_CLI/Runner.php(311): WP_CLI\Runner->run_command(Array, Array)
#8 phar:///usr/bin/wp/php/WP_CLI/Runn in phar:///usr/bin/wp/php/commands/core.php on line 190
````

i have tried this, and it does not work - from #1505 
````
rm -rf ~/.wp-cli/cache
````

**Comment by danielbachhuber** [comment]
Looking at this with fresh eyes, I don't think #1532 is the cause either. It appears the root is that cURL requests are failing on your box somehow. Were you able to track this down?
