### ISSUE TITLE
DOMAIN_CURRENT_SITE not being honored?

### ISSUE THREAD

**Issue by joshkoenig** [wp-cli/wp-cli#2058]
I have an instance where I'm trying to use WP-CLI without requiring the use of custom `--url` flags by having my wp-config.php cleverly set the right value for `DOMAIN_CURRENT_SITE`. However, it doesn't seem to be used, and I get the error from here:

https://github.com/wp-cli/wp-cli/blob/master/php/wp-settings-cli.php#L79

The site itself of course works fine. Can you suggest any reason why `DOMAIN_CURRENT_SITE` wouldn't work instead of the `--url` flag?

**Comment by danielbachhuber** [comment]
> I have an instance where I'm trying to use WP-CLI without requiring the use of custom --url flags by having my wp-config.php cleverly set the right value for DOMAIN_CURRENT_SITE.

Can you share the contents of `wp-config.php`, minus any secrets?

> Can you suggest any reason why DOMAIN_CURRENT_SITE wouldn't work instead of the --url flag?

There are many reasons it can fail. See the history of closed issues against #1631

**Comment by joshkoenig** [comment]
Thanks for the pointer! I'll review that thread now.

Here's the config with identifying info anonymized:

```
<?php
/**
 * This config file is yours to hack on. It will work out of the box on Pantheon
 * but you may find there are a lot of neat tricks to be used here.
 *
 * See our documentation for more details:
 *
 * http://helpdesk.getpantheon.com/
 */

/**
 * Local configuration information.
 *
 * If you are working in a local/desktop development environment and want to
 * keep your config separate, we recommend using a 'wp-config-local.php' file,
 * which you should also make sure you .gitignore.
 */
if (file_exists(dirname(__FILE__) . '/wp-config-local.php') && !isset($_ENV['PANTHEON_ENVIRONMENT'])):
  # IMPORTANT: ensure your local config does not include wp-settings.php
  require_once(dirname(__FILE__) . '/wp-config-local.php');

/**
 * Pantheon platform settings. Everything you need should already be set.
 */
else:
  if (isset($_ENV['PANTHEON_ENVIRONMENT'])):
    // ** MySQL settings - included in the Pantheon Environment ** //
    /** The name of the database for WordPress */
    define('DB_NAME', $_ENV['DB_NAME']);

    /** MySQL database username */
    define('DB_USER', $_ENV['DB_USER']);

    /** MySQL database password */
    define('DB_PASSWORD', $_ENV['DB_PASSWORD']);

    /** MySQL hostname; on Pantheon this includes a specific port number. */
    define('DB_HOST', $_ENV['DB_HOST'] . ':' . $_ENV['DB_PORT']);

    /** Database Charset to use in creating database tables. */
    define('DB_CHARSET', 'utf8');

    /** The Database Collate type. Don't change this if in doubt. */
    define('DB_COLLATE', '');

    /**#@+
     * Authentication Unique Keys and Salts.
     *
     * Change these to different unique phrases!
     * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
     * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
     *
     * Pantheon sets these values for you also. If you want to shuffle them you
     * can do so via your dashboard.
     *
     * @since 2.6.0
     */
    define('AUTH_KEY',         $_ENV['AUTH_KEY']);
    define('SECURE_AUTH_KEY',  $_ENV['SECURE_AUTH_KEY']);
    define('LOGGED_IN_KEY',    $_ENV['LOGGED_IN_KEY']);
    define('NONCE_KEY',        $_ENV['NONCE_KEY']);
    define('AUTH_SALT',        $_ENV['AUTH_SALT']);
    define('SECURE_AUTH_SALT', $_ENV['SECURE_AUTH_SALT']);
    define('LOGGED_IN_SALT',   $_ENV['LOGGED_IN_SALT']);
    define('NONCE_SALT',       $_ENV['NONCE_SALT']);
    /**#@-*/

    /** A couple extra tweaks to help things run well on Pantheon. **/
    if (isset($_SERVER['HTTP_HOST'])) {
      define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
      define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
    }
    // Don't show deprecations; useful under PHP 5.5
    error_reporting(E_ALL ^ E_DEPRECATED);

  else:
    /**
     * This block will be executed if you have NO wp-config-local.php and you
     * are NOT running on Pantheon. Insert alternate config here if necessary.
     *
     * If you are only running on Pantheon, you can ignore this block.
     */
    define('DB_NAME',          'database_name');
    define('DB_USER',          'database_username');
    define('DB_PASSWORD',      'database_password');
    define('DB_HOST',          'database_host');
    define('DB_CHARSET',       'utf8');
    define('DB_COLLATE',       '');
    define('AUTH_KEY',         'put your unique phrase here');
    define('SECURE_AUTH_KEY',  'put your unique phrase here');
    define('LOGGED_IN_KEY',    'put your unique phrase here');
    define('NONCE_KEY',        'put your unique phrase here');
    define('AUTH_SALT',        'put your unique phrase here');
    define('SECURE_AUTH_SALT', 'put your unique phrase here');
    define('LOGGED_IN_SALT',   'put your unique phrase here');
    define('NONCE_SALT',       'put your unique phrase here');
  endif;


    /**
     * WordPress Database Table prefix.
     *
     * You can have multiple installations in one database if you give each a unique
     * prefix. Only numbers, letters, and underscores please!
     */
    $table_prefix  = 'wp_';

    /**
     * WordPress Localized Language, defaults to English.
     *
     * Change this to localize WordPress. A corresponding MO file for the chosen
     * language must be installed to wp-content/languages. For example, install
     * de_DE.mo to wp-content/languages and set WPLANG to 'de_DE' to enable German
     * language support.
     */
    define('WPLANG', '');

    /**
     * For developers: WordPress debugging mode.
     *
     * Change this to true to enable the display of notices during development.
     * It is strongly recommended that plugin and theme developers use WP_DEBUG
     * in their development environments.
     *
     * You may want to examine $_ENV['PANTHEON_ENVIRONMENT'] to set this to be
     * "true" in dev, but false in test and live.
     */
    define('WP_DEBUG', false);

    /* That's all, stop editing! Happy Pressing. */



    define('RootDepth', 0);
    define('LimzMigration', false);

    define( 'SUNRISE', 'on' );

    /* Revisions */
    //define( 'WP_POST_REVISIONS', 0 );

    /* Multisite */
    define( 'WP_ALLOW_MULTISITE', true );

    define('MULTISITE', true);
    define('SUBDOMAIN_INSTALL', false);

    $environment = $_ENV['PANTHEON_ENVIRONMENT'];
    if($environment === 'live'){
        define('DOMAIN_CURRENT_SITE', 'www.foo.com');
    } else if($environment === 'test'){
        define('DOMAIN_CURRENT_SITE', 'pantheon-test.foo.com');
    } else if($environment === 'dev'){
        define('DOMAIN_CURRENT_SITE', 'pantheon-dev.foo.com');
    }

    define('PATH_CURRENT_SITE', '/');
    define('SITE_ID_CURRENT_SITE', 1);
    define('BLOG_ID_CURRENT_SITE', 1);

    /* That's all, stop editing! Happy blogging. */

    /** Absolute path to the WordPress directory. */
    if ( !defined('ABSPATH') )
        define('ABSPATH', dirname(__FILE__) . '/');

    /** Sets up WordPress vars and included files. */
    require_once(ABSPATH . 'wp-settings.php');

endif;
```

**Comment by danielbachhuber** [comment]
Maybe `$_ENV` isn't being set in CLI?

**Comment by joshkoenig** [comment]
I'll triple test for that, but considering it's how we do everything, and this same setup works in a few other contexts, I am pretty confident it is populated. ;)

**Comment by szepeviktor** [comment]
Try `var_dump`-ing `$this->get_wp_config_code()` here
https://github.com/wp-cli/wp-cli/blob/master/php/WP_CLI/Runner.php#L627

**Comment by danielbachhuber** [comment]
@joshkoenig Get this sorted out? Now that #2079 is landed, you might get better results by using nightly.

**Comment by joshkoenig** [comment]
I haven't had a chance to circle back (been out sick). I'll give it a look and report back. Thanks!

**Comment by danielbachhuber** [comment]
@joshkoenig Can you try again with WP-CLI nightly, and use `--debug` to get more verbosity out of the bootstrap process? #2138

**Comment by nbyloff** [comment]
@danielbachhuber I pulled a multisite DB from another environment and tried to do a search-replace after running the ```wp db import``` locally. Using the nightly build, ran the command below, with the results.

```javascript
vagrant@mydomain:/srv/www/mydomain.dev/current$ wp search-replace 'http://stg.mydomain.com' 'http://mydomain.dev' --skip-columns=guid --network --debug --url=mydomain.dev
Debug: No readable global config found (0.031s)
Debug: Using project config: /srv/www/mydomain.dev/current/wp-cli.yml (0.035s)
Debug: ABSPATH defined: /srv/www/mydomain.dev/current/web/wp/ (0.037s)
Debug: Set URL: mydomain.dev (0.04s)
Debug: Begin WordPress load (0.044s)
Debug: wp-config.php path: /srv/www/mydomain.dev/current/web/wp-config.php (0.046s)
PHP Warning:  Unterminated comment starting line 22 in phar:///usr/bin/wp/php/WP_CLI/Runner.php(731) : eval()'d code on line 22
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///usr/bin/wp/php/WP_CLI/Runner.php:697
Error: Site mydomain.dev not found.
vagrant@mydomain:/srv/www/mydomain.dev/current$
```

Running it a second time without the ```--url``` switch had the same results. 

```javascript
vagrant@mydomain:/srv/www/mydomain.dev/current$ wp search-replace 'http://stg.mydomain.com' 'http://mydomain.dev' --skip-columns=guid --network --debug
Debug: No readable global config found (0.032s)
Debug: Using project config: /srv/www/mydomain.dev/current/wp-cli.yml (0.036s)
Debug: ABSPATH defined: /srv/www/mydomain.dev/current/web/wp/ (0.039s)
Debug: Begin WordPress load (0.047s)
Debug: wp-config.php path: /srv/www/mydomain.dev/current/web/wp-config.php (0.049s)
PHP Warning:  Unterminated comment starting line 22 in phar:///usr/bin/wp/php/WP_CLI/Runner.php(731) : eval()'d code on line 22
PHP Stack trace:
PHP   1. {main}() /usr/bin/wp:0
PHP   2. include() /usr/bin/wp:4
PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///usr/bin/wp/php/WP_CLI/Runner.php:697
Debug: Set URL: mydomain.dev/ (0.11s)
Error: Site mydomain.dev/ not found.
vagrant@mydomain:/srv/www/mydomain.dev/current$
```

While ```search-replace``` isn't directly addressed in this ticket, you can see that it sets the URL, but throws an error ```Site: mydomain.dev not found```. Would this be related, or should I open another issue? Again, on the nightly build.

**Comment by cesarizu** [comment]
@danielbachhuber  I just tested this and, for me it's not working:

```
Debug (bootstrap): No readable global config found (0.012s)
Debug (bootstrap): Using project config: /home/user/src/project/wp-cli.local.yml (0.012s)
Debug (bootstrap): No package autoload found to load. (0.048s)
Debug (bootstrap): ABSPATH defined: /home/cesar/src/project/ (0.048s)
Debug (bootstrap): Begin WordPress load (0.049s)
Debug (bootstrap): wp-config.php path: /home/cesar/src/project/wp-config.php (0.049s)
PHP Notice:  Undefined index: DATABASE_URL in phar:///home/cesar/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 21
PHP Notice:  Undefined index: user in phar:///home/user/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 28
PHP Notice:  Undefined index: pass in phar:///home/user/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 31
PHP Notice:  Undefined index: host in phar:///home/user/bin/wp/php/WP_CLI/Runner.php(941) : eval()'d code on line 34
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /home/user/src/project/wp-includes/wp-db.php:1522
Stack trace:
#0 /home/user/src/project/wp-includes/wp-db.php(658): wpdb->db_connect()
#1 /home/user/src/project/wp-includes/load.php(371): wpdb->__construct(NULL, NULL, '', NULL)
#2 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(1085): require_wp_db()
#3 /home/user/src/project/wp-includes/plugin.php(235): WP_CLI\Runner->WP_CLI\{closure}(true)
#4 phar:///home/user/bin/wp/php/wp-settings-cli.php(91): apply_filters('enable_wp_debug...', true)
#5 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(962): require('phar:///home/ce...')
#6 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(904): WP_CLI\Runner->load_wordpress()
#7 phar:///home/user/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///home/user/bin/wp/php/boot-phar.php(5): include('phar:///home/us...')
#9 /home/user/bin/wp(4): include('phar:///home/u in /home/user/src/project/wp-includes/wp-db.php on line 1522
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/user/src/project/wp-includes/wp-db.php:1522
Stack trace:
#0 /home/user/src/project/wp-includes/wp-db.php(658): wpdb->db_connect()
#1 /home/user/src/project/wp-includes/load.php(371): wpdb->__construct(NULL, NULL, '', NULL)
#2 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(1085): require_wp_db()
#3 /home/user/src/project/wp-includes/plugin.php(235): WP_CLI\Runner->WP_CLI\{closure}(true)
#4 phar:///home/user/bin/wp/php/wp-settings-cli.php(91): apply_filters('enable_wp_debug...', true)
#5 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(962): require('phar:///home/us...')
#6 phar:///home/user/bin/wp/php/WP_CLI/Runner.php(904): WP_CLI\Runner->load_wordpress()
#7 phar:///home/user/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///home/user/bin/wp/php/boot-phar.php(5): include('phar:///home/us...')
#9 /home/user/bin/wp(4): include('phar:///home/u in /home/user/src/project/wp-includes/wp-db.php on line 1522
```

My wp-config.php contains: 

```
// ** Heroku Postgres settings - from Heroku Environment ** //
$db = parse_url($_ENV["DATABASE_URL"]);

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', trim($db["path"], "/"));

/** MySQL database username */
define('DB_USER', $db["user"]);

/** MySQL database password */
define('DB_PASSWORD', $db["pass"]);

/** MySQL hostname */
define('DB_HOST', $db["host"]);
```

**Comment by danielbachhuber** [comment]
Hi @cesarizu,

Github issues are no longer an appropriate venue for support questions. Please review http://wp-cli.org/#support
