### ISSUE TITLE
v0.21.1 while using redis persistent cache

### ISSUE THREAD

**Issue by entr** [wp-cli/wp-cli#2316]
I'm using redis object-cache from http://github.com/alleyinteractive/wp-redis/
Since v0.21.1 wp-cli commands fail like this:
```log
$ wp plugins list
PHP Fatal error:  Uncaught exception 'RedisException' with message 'Redis server went away' in @@@/staging/releases/20151221135201/web/app/object-cache.php:652
Stack trace:
#0 @@@/staging/releases/20151221135201/web/app/object-cache.php(652): Redis->exists('default:is_blog...')
#1 @@@/staging/releases/20151221135201/web/app/object-cache.php(478): WP_Object_Cache->_exists('default:is_blog...')
#2 @@@/staging/releases/20151221135201/web/app/object-cache.php(128): WP_Object_Cache->get('is_blog_install...', '', false, NULL)
#3 @@@/staging/releases/20151221135201/web/wp/wp-includes/functions.php(1350): wp_cache_get('is_blog_install...')
#4 /home/dev/.composer/vendor/wp-cli/wp-cli/php/utils-wp.php(8): is_blog_installed()
#5 /home/dev/.composer/vendor/wp-cli/wp-cli/php/wp-settings-cli.php(146): WP_CLI\Utils\wp_not_installed()
#6 /home/dev/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(736): require('/home/dev/.comp...')
#7 / in @@@/staging/releases/20151221135201/web/app/object-cache.php on line 652
```

```
$ wp core version
4.4
```
```log
$ php --version
PHP 5.6.10 (cli) (built: Jul  2 2015 20:12:43) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

I'm using the Redis php extension https://github.com/phpredis/phpredis
Had to downgrade to v0.20.4 to get it working again.

**Comment by danielbachhuber** [comment]
Couple of things:

1. You'll need to globalize your `$redis_server` in `wp-config.php`:

```
global $redis_server;
$redis_server = array( 'foo' => 'bar' );
```

2. You should use the Pantheon fork of the Redis object cache drop-in, as it's actively maintained: https://github.com/pantheon-systems/wp-redis

**Comment by entr** [comment]
Can't reproduce using https://github.com/pantheon-systems/wp-redis
Thanks.
