### ISSUE TITLE
Getting fatal error when running `wp export`

### ISSUE THREAD

**Issue by vodou** [wp-cli/wp-cli#3363]
Hi,

When I try to run `wp export` on my site, I get a fatal error:

`PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php:147`

Here's the full debug output from `wp export --debug`:

```
Debug (bootstrap): No readable global config found (0.007s)
Debug (bootstrap): No project config found (0.007s)
Debug (bootstrap): No package autoload found to load. (0.037s)
Debug (bootstrap): ABSPATH defined: /srv/www/vhosts/example.com/ (0.037s)
Debug (bootstrap): Begin WordPress load (0.037s)
Debug (bootstrap): wp-config.php path: /srv/www/vhosts/example.com/wp-config.php (0.037s)
Debug (bootstrap): Set URL: example.com/ (0.038s)
Debug (bootstrap): Loaded WordPress (0.404s)
Debug (bootstrap): Running command: export (0.404s)
Starting export process...
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php:147
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php(15): Oxymel->init_new_dom()
#1 phar:///usr/local/bin/wp/php/export/class-wp-export-wxr-formatter.php(42): Oxymel->__construct()
#2 phar:///usr/local/bin/wp/php/export/class-wp-export-wxr-formatter.php(22): WP_Export_WXR_Formatter->header()
#3 phar:///usr/local/bin/wp/php/export/writers.php(129): WP_Export_WXR_Formatter->before_posts()
#4 phar:///usr/local/bin/wp/php/export/functions.export.php(13): WP_Export_Split_Files_Writer->__construct(Object(WP_Export_WXR_Formatter), Array)
#5 phar:///usr/local/bin/wp/php/commands/export.php(138): wp_export(Array)
#6 [internal function]: Export_Command->__invoke(Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#9 phar:///usr/lo in phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php on line 147
Fatal error: Uncaught Error: Class 'DOMDocument' not found in phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php:147
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php(15): Oxymel->init_new_dom()
#1 phar:///usr/local/bin/wp/php/export/class-wp-export-wxr-formatter.php(42): Oxymel->__construct()
#2 phar:///usr/local/bin/wp/php/export/class-wp-export-wxr-formatter.php(22): WP_Export_WXR_Formatter->header()
#3 phar:///usr/local/bin/wp/php/export/writers.php(129): WP_Export_WXR_Formatter->before_posts()
#4 phar:///usr/local/bin/wp/php/export/functions.export.php(13): WP_Export_Split_Files_Writer->__construct(Object(WP_Export_WXR_Formatter), Array)
#5 phar:///usr/local/bin/wp/php/commands/export.php(138): wp_export(Array)
#6 [internal function]: Export_Command->__invoke(Array, Array)
#7 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#9 phar:///usr/lo in phar:///usr/local/bin/wp/vendor/nb/oxymel/Oxymel.php on line 147
```
System details:

```
% wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.8-0ubuntu0.16.04.2
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

% uname -a
Linux Web-01 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

% which -a php
/usr/bin/php

% php -v
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

% stat $(which wp)
  File: '/usr/local/bin/wp'
  Size: 4967063   	Blocks: 9704       IO Block: 4096   regular file
Device: fc00h/64512d	Inode: 225         Links: 1
Access: (0775/-rwxrwxr-x)  Uid: ( 1001/johanneson)   Gid: ( 1001/johanneson)
Access: 2016-08-31 11:11:49.936470262 -0500
Modify: 2016-08-18 10:46:57.618346722 -0500
Change: 2016-08-18 10:47:44.810245972 -0500
 Birth: -

% grep '^\$wp_version\s' wp-includes/version.php 
$wp_version = '4.5.3';

% wp package list
+------+-------------+---------+---------+
| name | description | authors | version |
+------+-------------+---------+---------+
+------+-------------+---------+---------+
```

I *am* able to export a site via the WordPress backend, but I've got 200+ sites to export.

**Comment by vodou** [comment]
Solution:

Install `php-dom`.

In my case it was `apt-get install php-dom`; others may need `apt-get install php5-dom`.
