### ISSUE TITLE
WP-CLI's use of composer is interfering with site's usage of composer

### ISSUE THREAD

**Issue by AaronHolbrook** [wp-cli/wp-cli#4632]
I am running into an issue with WP CLI and composer.

It appears to be due to WP CLI now utilizing composer prior to loading the WP application logic. More specifically, as I am using composer myself in my application logic to load and handle my own dependencies, when it comes time to call upon a class that should be auto-loadable it fatals out as it is unable to find it.

Steps to reproduce:
1. In wp-content/ create a composer.json file with the following:
```json
{
	"config": {
		"preferred-install": "dist",
		"vendor-dir": "mu-plugins/app/vendor"
	},
	"extra": {
		"installer-paths": {
			"mu-plugins/{$name}/": [
				"type:wordpress-muplugin"
			]
		}
	},
	"require": {
		"php": ">=5.5",
		"composer/installers": "~1.0.12",
		"arrilot/dotenv-php": "^1.0"
	}
}
```

2. In `wp-content/mu-plugins/` create the directory `app` and a file inside `app.php` with the following:

```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
/**
 * Load dotenv if .env file is present
 */
$vars = Arrilot\DotEnv\DotEnv::all();
```

3. Load `mu-plugins/app/app.php` by creating a `load.php` in `mu-plugins/load.php` with the following:
```php
<?php
require_once __DIR__ . '/app/app.php';
```

4. Run `composer update` at the `wp-content/` directory path.

5. Load the site in a browser, see that it loads correctly/fine and properly executes the `app.php` logic.

6. Attempt to run `wp` on the same site, and see that it fatals on the `Arrilot\DotEnv\DotEnv` load attempt:

```
Fatal error: Uncaught Error: Class 'Arrilot\DotEnv\DotEnv' not found in /var/www/html/sites/wordpress/htdocs/wp-content/mu-plugins/app/app.php:8
Stack trace:
#0 /var/www/html/sites/wordpress/htdocs/wp-content/mu-plugins/load.php(2): require_once()
#1 /var/www/html/sites/wordpress/htdocs/wp-settings.php(260): include_once('/var/www/html/s...')
#2 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1105): require('/var/www/html/s...')
#3 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1032): WP_CLI\Runner->load_wordpress()
#4 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#5 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#6 phar:///usr/local/bin/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#7 phar:///usr/local/bin/wp/php/boot-phar.php(8): include('phar:///usr/loc...')
#8 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#9 {main}
  thrown in /var/www/html/sites/wordpress/htdocs/wp-content/mu-plugins/app/app.php on line 8
```

**Comment by schlessera** [comment]
@AaronHolbrook I suspect this is a problem with your Composer setup, which only happens to work in a certain loading order.

However, it is difficult to tell as you omitted the autoloading configuration from the `composer.json` file. Is it possible to see the complete `composer.json` file (the one you're actually using)?

**Comment by AaronHolbrook** [comment]
Hey @schlessera,
Appreciate the feedback, I think you are right, one of our other engineers is unable to produce this following the steps above.

I've tested this with version 1.4.0 and 1.4.1 of wp-cli. I've also tried deleting and reinstalling wp-cli following the CURL recommended method here: https://make.wordpress.org/cli/handbook/installing/

The problem persists still.

There is no autoloading configuration from any of my composer.json files. The steps and file I listed above create the issue (unless there's something else you'd need to see).

Here is the composer.lock file that is generated from that install: https://gist.github.com/AaronHolbrook/18ecb569d865cc217776789a377e8b3d#file-composer-lock

And the entire composer.json file:
https://gist.github.com/AaronHolbrook/18ecb569d865cc217776789a377e8b3d#file-composer-json

**Comment by remcotolsma** [comment]
I'm having the same issue with a WordPress plugin which is using Composer PSR-4 autoload feature. The plugin and autoloading of classes is working good if we use WordPress frontend/backend. If we use for example WP-CLI command `wp plugin list` we get class loading issues:

```
➜  pay.test git:(develop) ✗ wp plugin list
PHP Warning:  Class '\Pronamic\WordPress\Pay\Plugin' not found in /Users/remco/Workspace/wp-pronamic-ideal/includes/deprecated-classes.php on line 3
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar:0
PHP   2. include() /usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar:4
PHP   3. include() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/boot-phar.php:8
PHP   4. WP_CLI\bootstrap() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/wp-cli.php:23
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/bootstrap.php:75
PHP   6. WP_CLI\Runner->start() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/WP_CLI/Bootstrap/LaunchRunner.php:23
PHP   7. WP_CLI\Runner->load_wordpress() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/WP_CLI/Runner.php:1032
PHP   8. require() phar:///usr/local/Cellar/wp-cli/1.4.1/libexec/wp-cli-1.4.1.phar/php/WP_CLI/Runner.php:1105
PHP   9. include_once() /Users/remco/Websites/pay.test/wp-settings.php:305
PHP  10. require_once() /Users/remco/Workspace/wp-pronamic-ideal/pronamic-ideal.php:55
PHP  11. ComposerAutoloaderInitae6bf1b5c0d5bd9784c168d0e08d8978::getLoader() /Users/remco/Workspace/wp-pronamic-ideal/vendor/autoload.php:7
PHP  12. composerRequireae6bf1b5c0d5bd9784c168d0e08d8978() /Users/remco/Workspace/wp-pronamic-ideal/vendor/composer/autoload_real.php:60
PHP  13. require() /Users/remco/Workspace/wp-pronamic-ideal/vendor/composer/autoload_real.php:70
PHP  14. class_alias() /Users/remco/Workspace/wp-pronamic-ideal/includes/deprecated-classes.php:3
```

I have installed WP CLI with `brew install wp-cli`, if i use the WP CLI Git clone of the `release-1-4-1` branch i don't have this issue:

![schermafbeelding 2018-01-25 om 13 25 16](https://user-images.githubusercontent.com/869674/35388344-b299d218-01d3-11e8-846f-4ef5f8602fa2.png)

A colleague of my has the same setup but he is not having issues when running `wp plugin list`.

**Comment by remcotolsma** [comment]
I just also tried the `composer require wp-cli/wp-cli` version of WP CLI and this version is also working. Only the WP CLI version installed with `brew install wp-cli` is giving this issue on my setup.

![schermafbeelding 2018-01-25 om 13 37 39](https://user-images.githubusercontent.com/869674/35388712-26a12976-01d5-11e8-9b97-d11f3dd49689.png)

**Comment by remcotolsma** [comment]
Also tried the nightly version of WP CLI:

```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
```

Same issue:

```
php wp-cli-nightly.phar plugin list
```

![schermafbeelding 2018-01-25 om 14 01 01](https://user-images.githubusercontent.com/869674/35389497-3971609a-01d8-11e8-9b4e-41f88f6aedea.png)

**Comment by AaronHolbrook** [comment]
Installing the git source version works:

![](https://d.pr/i/UppwIu+)

**Comment by remcotolsma** [comment]
Maybe it's related to used Composer version? The Phar build of WP CLI is shipped with Composer version `1.5.2`?

```
wp eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.5.2
```

```
./vendor/bin/wp eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.6.2
```

````
php wp-cli.phar eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.5.2
```

```
php wp-cli-nightly.phar eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.5.6
```

![schermafbeelding 2018-01-25 om 16 05 31](https://user-images.githubusercontent.com/869674/35395062-977428e2-01e9-11e8-9091-c4bcfd3780ea.png)

https://github.com/composer/composer/blob/master/CHANGELOG.md

Maybe update to Composer version `1.6.2`?
https://github.com/wp-cli/wp-cli/blob/master/composer.json#L25

```
composer outdated
```

![schermafbeelding 2018-01-25 om 16 08 58](https://user-images.githubusercontent.com/869674/35395232-18b79e0c-01ea-11e8-8b93-f5439a84c832.png)

**Comment by remcotolsma** [comment]
Composer version doesn't seems to make a difference:

```
➜ composer require composer/composer 1.6.2

➜ ./vendor/bin/wp eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.6.2

➜ ./vendor/bin/wp plugin list
+----------------+----------+--------+---------+
| name           | status   | update | version |
+----------------+----------+--------+---------+
| akismet        | inactive | none   | 4.0.2   |
| hello          | inactive | none   | 1.6     |
| pronamic-ideal | active   | none   | 4.7.0   |
+----------------+----------+--------+---------+
```

![schermafbeelding 2018-01-25 om 16 34 03](https://user-images.githubusercontent.com/869674/35396664-9bc96d0e-01ed-11e8-9ef5-49a5f365b90f.png)

```
➜ composer require composer/composer 1.5.2

➜ ./vendor/bin/wp eval 'echo Composer\Composer::VERSION;' --skip-plugins
1.5.2

➜ ./vendor/bin/wp plugin list
+----------------+----------+--------+---------+
| name           | status   | update | version |
+----------------+----------+--------+---------+
| akismet        | inactive | none   | 4.0.2   |
| hello          | inactive | none   | 1.6     |
| pronamic-ideal | active   | none   | 4.7.0   |
+----------------+----------+--------+---------+
```

![schermafbeelding 2018-01-25 om 16 26 30](https://user-images.githubusercontent.com/869674/35396676-a2897706-01ed-11e8-8247-fd07a7b2b728.png)

**Comment by remcotolsma** [comment]
If i generate my own WP CLI Phar build it is also working:

```
➜ php -dphar.readonly=0 ./wp-cli/utils/make-phar.php test.phar

➜ php test.phar --version
WP-CLI 1.5.0-alpha

➜ php test.phar plugin list
+----------------+----------+--------+---------+
| name           | status   | update | version |
+----------------+----------+--------+---------+
| akismet        | inactive | none   | 4.0.2   |
| hello          | inactive | none   | 1.6     |
| pronamic-ideal | active   | none   | 4.7.0   |
+----------------+----------+--------+---------+
```

So no idea why official Phar builds have this issue.

* https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
* https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar

**Comment by schlessera** [comment]
Where and how do you load your Composer autoloader?
Did you do modifications to the `wp-config.php` file?

**Comment by schlessera** [comment]
@remcotolsma From your debug trace, I assume you're using a `"files"` segment in your Composer's autoloader, which adds class aliases.

Are you aware that the `"files"` segment in the Composer autoloader is not actually an autoloader, but rather a hard include as soon as that file is parsed?

**Comment by remcotolsma** [comment]
In my case we load the Composer autoloader file in the plugin file.

```
require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload.php';
```

I don't have special modifications in the `wp-config.php`.

> Are you aware that the "files" segment in the Composer autoloader is not actually an autoloader, but rather a hard include as soon as that file is parsed?

Yes, i know, but also without the `files` segment i have the same issue.

**Comment by AaronHolbrook** [comment]
I don't have any modifications in wp-config.php.

I am not loading any files in my composer.json, however one of the packages I bring in is doing so.

**Comment by remcotolsma** [comment]
I just tried to reproduce the problem on another machine, but unfortunately i can't reproduce this issue on that machine. Also tried to reproduce this issue on Travis CI but als with no luck: https://travis-ci.org/remcotolsma/wp-cli-composer-issue. I'm out of ideas for now.

**Comment by schlessera** [comment]
Did you try clearing all Composer caches?
Did you try with a clean `~/.composer` folder?

**Comment by AaronHolbrook** [comment]
Yes to both

**Comment by remcotolsma** [comment]
I removed the `vendor` dir from the plugin and run `composer clear-cache` and `composer install`, this fixed the issue for me.

**Comment by schlessera** [comment]
@AaronHolbrook Do you have any new insights re. the above? Most importantly, did you find a reproducible way of triggering this?

**Comment by hews** [comment]
Also having this error: appeared out of the blue.

**Comment by hews** [comment]
Note: was able to fix it. In my case this came from having something out of sync in my Composer install (not hard as I'm using a Bedrock-style repo inside containers, where in dev I am bind-mounting my codebase). Had to `rm -rf vendor/`, `.../plugins/*` & `.../mu-plugins/*`, `composer.lock` (except the Bedrock mu-plugin loader) and my caches on my host and containers, then re-run Composer. Turns out some files *within the plugins* were out of sync in terms of versions.

**Comment by AaronHolbrook** [comment]
@schlessera: I do not have any new insights, every time I run `wp` it reproduces it, I'm not sure what you mean by finding a reproducible way of triggering it.

I have also tried running `composer clear-cache` and `composer install` and it does NOT fix this issue.

**Comment by gitlost** [comment]
@AaronHolbrook I followed your steps and couldn't reproduce it. The `composer.lock` generated was the exact same as the one you posted. I suppose something to do to debug what's happening would be to add a dump of the autoload functions:
```
error_log( __FILE__ . " spl_autoload_functions=" . print_r( spl_autoload_functions(), true ) );
```
to `wp-content/mu-plugins/app/app.php` after the `require_once __DIR__ . '/vendor/autoload.php';` line and compare the failing phar case to the succeeding git case...

**Comment by andrejpavlovic** [comment]
I came across this issue as well using WP-CLI 2.0.1. After some debugging, it looks like WP-CLI does some manual search/replace of \_\_DIR__ in the wp-config.php file and then does an eval() of it.

Not sure why but manually executing something like `php ..\vendor\wp-cli\wp-cli\php\boot-fs.php plugin list` would work, while excuting `wp plugin list` would not be able to autoload my classes (my autoload.php would not even be executed).

The workaround I found was to wrap the require_once with `realpath`. Maybe this helps someone.
Before: `require_once __DIR__ . '/../vendor/autoload.php';`
After: `require_once realpath(__DIR__ . '/../vendor/autoload.php');`

Note, I was using Windows, but maybe it would help on Linux too.

**Comment by andrejpavlovic** [comment]
@schlessera The error I get is that a class that is supposed to be autoloaded is missing. I added an echo statement to my `autoload.php` file just to see if it gets loaded at all, and it doesn't echo the statement. It only echo's it if I make the fix above. So it's strange that the file isn't included at all and yet doesn't throw an error that it couldn't find the file.

Actually things get even more interesting. So if I rename my autoload file from `autoload.php` to `autoload2.php` and include that, everything works fine! When I run `print_r(get_included_files());` the file doesn't show up when I use `autoload.php`, but it does show up when using `autoload2.php`.

**Comment by schlessera** [comment]
@andrejpavlovic 
> If not, can you try to replace require_once with require to see what happens?

Did you try this?

**Comment by andrejpavlovic** [comment]
@schlessera Yeah didn't make a difference.

**Comment by leonstafford** [comment]
Also encountered this on a specific environment:

 - OpenBSD
 - chroot'ed web root
 - plugins and site root symlinked to allow php/wp-cli to handle paths
 - multiple PSR-4 autoloaded plugins, same namespace

Failed to load 2nd plugin after clearing caches. 

Clean clone and composer install of both plugins on another machine (Digital Ocean Ubuntu 18.04 WP image) did not produce the issue.

**Comment by schlessera** [comment]
I suspect this issue could ultimately be retraced to the `wp-cli/autoload-splitter`, and more specifically its automatic setting of the Composer `--optimize` flag, meaning it forced the use of classmaps.

Since WP-CLI version v2.0.0, this is not being used anymore (it was just a hack to get around package structure issues in a BC way). Can anyone still reproduce this issue with WP-CLI v2?

**Comment by rwky** [comment]
Just encountered this with 2.4.0. 

```
OS:     Linux 5.4.0-1015-aws #15-Ubuntu SMP Thu Jun 4 22:47:00 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.3
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /srv/www/wordpress
WP-CLI packages dir:
WP-CLI global config:   /root/.wp-cli/config.yml
WP-CLI project config:
```
I had to replace:

`require_once('vendor/autoload.php');`

With:

`require_once(realpath(__DIR__ . '/vendor/autoload.php'));`

In wp-config.php 

Thanks to @andrejpavlovic

**Comment by stefanfisk** [comment]
I ended up here after trying to figure out why `symfony/polyfill-mbstring` was not providing `mb_ucfirst()` when running `wp`  in production. My issue probably has a different root cause, but I figured I add it here so that anyone else experiencing something similar might find it...

In my case the issue was that I am calling `./vendor/bin/wp` locally but `/usr/local/bin` in production. Since WP CLI bundles an older version of `symfony/polyfill-mbstring` that does not provide `mb_ucfirst()` the autoloader silently used the old version. This happens because the polyfills are provided via a static file, and both versions get the same static file identifier in `$GLOBALS['__composer_autoload_files']`.

The solution was to add `require: vendor/autoload.php` to `wp-cli.yml`. Since I'm also installing `wp-cli/wp-cli-bundle` via composer I assume that my dependencies will be compatible.

**Comment by yCodeTech** [comment]
I've run into this issue on the latest version (2.11.0) on Windows 10. My setup includes the instalment of various CLIs globally on composer (`composer global require ...`). 2 packages I require globally are Valet (windows port) and WP_CLI. Valet has dependencies of Laravel components (`illuminate\...`). 

Project-wise, I use a Roots Bedrock and Sage WP installation, which installs dependencies of Laravel Components into each project.
Using WP_CLI in such a project it resolves the classes from the globally installed dependencies, which then gives me the errors similar to what the OP mentioned.

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\{closure}() must be an instance of Roots\Sage\Container, instance of Illuminate\Container\Container given`

I've managed to fix the issue by installing WP_CLI in the project itself and using the projects vendor's bin instead of the global CLI, works perfectly.

**Comment by cklosowski** [comment]
@BrianHenryIE and I picked this up at WCUS contributor day. @schlessera would value
your read, since you triaged this one originally, and @swissspidy tagging you for the
#6238 interaction below.

**Nothing here is a new diagnosis.** @stefanfisk had it right in
[2024](https://github.com/wp-cli/wp-cli/issues/4632#issuecomment-2441048458): the
shared `$GLOBALS['__composer_autoload_files']` key with a version-independent
identifier. @schlessera's hunch about the `"files"` segment, @remcotolsma's "phar
fails but `vendor/bin/wp` works", and @yCodeTech's global-versus-project conflict are
all the same cause. We just made it reproducible.

## 30 seconds, no WordPress, no Docker (needs PHP < 8.4)

```bash
mkdir -p /tmp/4632/{phar,site} && cd /tmp/4632
printf '{"require":{"symfony/polyfill-mbstring":"1.28.0"}}' > phar/composer.json
printf '{"require":{"symfony/polyfill-mbstring":"1.31.0"}}' > site/composer.json
(cd phar && composer install -q) && (cd site && composer install -q)

php -r 'require "/tmp/4632/phar/vendor/autoload.php";  // WP-CLI tree, loads first
        require "/tmp/4632/site/vendor/autoload.php";  // site plugin, loads second
        echo (new ReflectionClass(Symfony\Polyfill\Mbstring\Mbstring::class))->getFileName(), "\n";
        echo function_exists("mb_ucfirst") ? "yes" : "NO", "\n";'
```

```
/tmp/4632/site/vendor/symfony/polyfill-mbstring/Mbstring.php
NO
```

1.31.0's class is live, yet 1.31.0's `mb_ucfirst()` is missing. The site's tree
loaded alone gives `yes`.

Both installs generate the identical `files` identifier,
`0e6d7bf4a5811bfa5cf40c5ccd6fae6a`, because it hashes package name plus relative
path and excludes the version. Classes resolve last-wins, since `register(true)`
prepends, while `files` resolve first-wins. Opposite directions, so you end up with
one version's classes and the other version's bootstrap. Reordering only flips which
symbol breaks. The 2.12.0 phar claims that same key.

## Why now: #6238 makes it fatal

On any WordPress install with a 2.x `wp` on `PATH`:

```bash
cd wp-content/plugins/some-active-plugin
composer require wp-cli/wp-cli:dev-main
wp plugin list      # Error: Invalid format: table
```

#6238 replaced `Formatter`'s switch with a static registry populated by a new
bootstrap step, `InitializeFormatter`. 2.x has no such step, so the project's 3.0
`Formatter` wins the class lookup and its registry is never filled.
`--skip-wordpress` succeeds. (`table` is a valid case in every release from v2.0.0
through v2.12.0 and there is no v2.13, so 2.x-to-2.x skew cannot cause this.)

No criticism of #6238 intended, the registry is the better design. It just turns
this collision from survivable into a stop on the most basic command.

## One question

We built a project-side guard that clears `WP_CLI\` from any non-phar registered
loader, and it removes the fatal. But a project cannot know which of its prefixes are
safe to surrender, while WP-CLI knows what it shipped, so it probably belongs in the
runner after `load_wordpress()`.

@schlessera @swissspidy would either shape be welcome as a PR?

- **diagnostic only**: detect the second copy, error clearly, no loading change
- **active**: neutralize the competing WP-CLI prefixes

Happy to build either, happy to be told neither, and happy to open it against `main`
separately if you would rather leave this issue untouched.

One triage note if it helps: this issue holds three different problems, the collision
above, the `wp-config.php` `eval()` mode (@andrejpavlovic, @rwky), and several
genuinely local cache and symlink cases. We suspect that conflation is why the
reproducible one never got confirmed. Glad to split it.

**Comment by swissspidy** [comment]
Thanks for testing! Let me try to add some follow-up improvements for #6238 to improve the behavior there for Composer installs.
