### ISSUE TITLE
Curls Error when using Requests Library

### ISSUE THREAD

**Issue by derweili** [wp-cli/wp-cli#5118]
When using the Requests Library with `Requests::get( $url )` I get an error:

```
[02-Aug-2017 02:26:28 UTC] PHP Fatal error:  Uncaught Requests_Exception: cURL error 77: error setting certificate verify locations:
  CAfile: phar:///usr/bin/wp/vendor/rmccue/requests/library/Requests/Transport/cacert.pem
  CApath: /etc/ssl/certs in phar:///usr/bin/wp/vendor/rmccue/requests/library/Requests/Transport/cURL.php:422
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.1.0/bin/wp/vendor/rmccue/requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array)
#1 phar:///usr/local/Cellar/wp-cli/2.1.0/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_cURL->request('https://fairdom...', Array, NULL, Array)
#2 phar:///usr/local/Cellar/wp-cli/2.1.0/bin/wp/vendor/rmccue/requests/library/Requests.php(231): Requests::request('https://fairdom...', Array, NULL, 'GET', Array)
#3 /Users/werbeagenten/Sites/wordpress-test/wp-content/plugins/hits-publications-api/inc/api.php(51): Requests::get('https://fairdom...')
#4 /Users/werbe in phar:///usr/local/Cellar/wp-cli/2.1.0/bin/wp/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 422
```

Using `wp_remote_get()`works well.

Related issue: https://github.com/wp-cli/eval-command/issues/8

**Comment by schlessera** [comment]
I assume this is caused by our use of our own Requests package, which is then missing the explicit setting of the WP certificate location.

The fix might be as simple as copying WP's explicit setting into WP-CLI as well.

**Comment by selim13** [comment]
I'm writing some maintenance scripts that use Request and facing the same problem. 
The simple solution was to manually set the path to certificates.
```php
if (defined('WP_CLI') && WP_CLI) {
    Requests::set_certificate_path(ABSPATH . WPINC . '/certificates/ca-bundle.crt');

    \WP_CLI::add_command('cmd', new Cmd());
}
```

**Comment by broskees** [comment]
Quick copypasta mu-plugin:
```php
<?php
/**
 * Fatal error: Uncaught Requests_Exception: cURL error 77: error setting certificate verify locations...
 * 
 * This is a fix found in: https://github.com/wp-cli/wp-cli/issues/5118
 */

!defined('ABSPATH') && exit();

if (!defined('WP_CLI') || !WP_CLI) {
    return;
}

Requests::set_certificate_path(ABSPATH . WPINC . '/certificates/ca-bundle.crt');
```

**Comment by danielbachhuber** [comment]
@broskees @selim13 @derweili Is this still an issue? If so, can you provide some steps to reproduce it?

**Comment by danielbachhuber** [comment]
I can reproduce this error with a `test.php` file:

```php
<?php

$response = Requests::get( 'https://example.com' );
```

The nightly Phar produces this error:

```bash
$ php wp-cli-nightly.phar eval-file --skip-wordpress test.php

Fatal error: Uncaught Requests_Exception: cURL error 77: error setting certificate verify locations:  CAfile: phar:///Users/danielbachhuber/Desktop/wp-cli-nightly.phar/vendor/rmccue/requests/library/Requests/Transport/cacert.pem CApath: none in phar:///Users/danielbachhuber/Desktop/wp-cli-nightly.phar/vendor/rmccue/requests/library/Requests/Transport/cURL.php:443
```

`wp-cli-dev` works fine though:

```bash
$ wp eval-file --skip-wordpress test.php
HTTP code 200
```

**Comment by danielbachhuber** [comment]
It looks like the `cacert.pem` file is properly embedded in the Phar:

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/36432/221710012-0bc4fcd8-91c0-438c-9fff-2f2ec9f0ad43.png">

https://github.com/wp-cli/wp-cli-bundle/blob/0e4508cc90d1cff8fa4c9fbc1121c98a2d6c7702/utils/make-phar.php#L293

**Comment by danielbachhuber** [comment]
As it turns out, WP-CLI already has some solution bundle for this:

https://github.com/wp-cli/wp-cli/blob/bbb6131254e08c3c60ab33b4c89228b27a69496e/php/utils.php#L759-L772

Here's a `test.php` script that works:

```php
<?php
$response = Requests::get(
	'https://example.com',
	array(),
	array( 'verify' => WP_CLI\Utils\get_default_cacert() )
);
WP_CLI::log( sprintf( 'HTTP code %s', $response->status_code ) );
```

You can also simply use `WP_CLI\Utils\http_request()`: https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-utils-http-request/
