### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Requests_Hooks' not found in phar://....

### ISSUE THREAD

**Issue by MoOx** [wp-cli/wp-cli#5295]
I am trying to use wp-cli to download wordpress export file.
I did the following

```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
php wp-cli.phar --info
chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/local/bin/wp
php -d memory_limit=512M wp package install wp-cli/restful
wp export --http=https://my-host
```

and just got

```

Fatal error: Uncaught Error: Class 'Requests_Hooks' not found in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php:568
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(363): Requests::set_defaults('http://dame.bio', Array, NULL, 'HEAD', Array)
wp-cli/restful#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(623): Requests::request('http://dame.bio', Array, NULL, 'HEAD', Array)
wp-cli/restful#2 /~/.wp-cli/packages/vendor/wp-cli/restful/inc/Runner.php(94): WP_CLI\Utils\http_request('HEAD', 'http://dame.bio')
wp-cli/restful#3 /~/.wp-cli/packages/vendor/wp-cli/restful/inc/Runner.php(22): WP_REST_CLI\Runner::auto_discover_api('http://dame.bio')
wp-cli/restful#4 /~/.wp-cli/packages/vendor/wp-cli/restful/wp-rest-cli.php(10): WP_REST_CLI\Runner::load_remote_commands()
wp-cli/restful#5 /~/.wp-cli/packages/vendor/composer/autoload_real.php(66): require('/~/.wp...')
wp-cli/restful#6 /~/.wp-cli/packages/vendor/composer/autoload_real.php(56): composerRequire86500668dbb2581e1c0704f41a37ea4e('22bd962 in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php on line 568
```

**Comment by hilt86** [comment]
Thanks so much @schlessera, much appreciated! When can I expect the updated version pushed to homebrew / docker, etc?
