### ISSUE TITLE
version higher than expected

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/wp-cli#5320]
wp-cli seems to always only access the download server of WordPress and not to use the download server of the manufacturer when it comes to paid plug-ins. This leads to errors such as "version higher than expected" because plug-in manufacturers often use the same technical name for paid versions on their own download server.

Is my assumption true that wp-cli accesses only the download server of WordPress and does not read the required server?

**Comment by wixaw** [comment]
I have same problem :+1:

**Comment by rotarymetronyc** [comment]
We have the same problem. Happens with the updraft plugin, reporting as the installed version "2.16.24.24" and always listed as "version higher than expected".

**Comment by sebastienserre** [comment]
Hello,
I had the same issue this morning with WooCommerce which is in wp.org

**Comment by tomaskavalek** [comment]
Same issue for me. If I want to simply disable updates of any plugin, I change its version to very high – for ex. 1.0.4 –> 1000.0.4. After upgrade to 2.4.0 – version higher than expected.

**Comment by afragen** [comment]
@schlessera I think I'm having this same issue. But perhaps I can provide some more information.

My Git Updater/Git Updater PRO provides WP-CLI function for updating and installing, and has for years now. Since WP 2.5.0 I get the same _version higher than expected_ in the `wp plugin list` for every plugin that is being managed by Git Updater.

Additionally I get the following error.

```
Notice: Undefined property: stdClass::$new_version in phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 698

Call Stack:
    0.0017     230528   1. {main}() /opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp:0
    0.0159     762624   2. include('phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/php/boot-phar.php') /opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp:4
    0.0161     763592   3. include('phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php') phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/php/boot-phar.php:11
    0.0166     770656   4. WP_CLI\bootstrap() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
    0.2023    3974000   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:77
    0.2023    3974720   6. WP_CLI\Runner->start() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23
    1.0791   18182632   7. WP_CLI\Runner->run_command_and_exit() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1194
    1.0791   18182952   8. WP_CLI\Runner->run_command() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:422
    1.0794   18189968   9. WP_CLI\Dispatcher\Subcommand->invoke() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:399
    1.0891   18450576  10. call_user_func:{phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491}() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
    1.0891   18450648  11. WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
    1.0909   18465032  12. call_user_func:{phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100}() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
    1.0909   18465096  13. Plugin_Command->list_() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:100
    1.0909   18465288  14. WP_CLI\CommandWithUpgrade->_list() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:1128
    1.1017   18450544  15. Plugin_Command->get_all_items() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/extension-command/src/WP_CLI/CommandWithUpgrade.php:479
    1.1017   18450768  16. Plugin_Command->get_item_list() phar:///opt/homebrew/Cellar/wp-cli/2.5.0/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php:229
```

This is repeated several times. This is on WP-CLI 2.5.0

**Comment by banditrider** [comment]
Same here - so far for Updraft Plus and Woocommerce Email Test Pro. Super annoying, because no plugins are updated at all, when this happens.

**Comment by infocube-dev-team** [comment]
I have the same issue for my 3rd party theme 
The issue is related to WPCLI, WP core ( theme_api() ) and the theme producer, which have not implemented the theme_api hook response. I think the same behavior is valid also for plugins, I have to check them 

I used a workaround to fix it (maybe not so pretty)
I think you can change/extend it to handle your paid plugins too



	add_filter( 'themes_api', function ( $res, $action, $args ) {
	      if ( $action == 'theme_information' ) {
		      if (  $args->slug == 'my_theme'  ) {
			      $res = true;
		      }
	      }
	      return $res;
	}, 3, 9999 );

        add_filter( 'themes_api_result', function ( $res, $action, $args ) {
	        if ( $action == 'theme_information' ) {
		      if (  $args->slug == 'my_theme'  ) {
			        return new WP_Error( "Disabled Theme API Result" );
		        }
	        }
        
	        return $res;
        }, 3, 9999 );

**Comment by knofte** [comment]
Where did you add this mate? :)
(which file, location etc)

> I have the same issue for my 3rd party theme The issue is related to WPCLI, WP core ( theme_api() ) and the theme producer, which have not implemented the theme_api hook response. I think the same behavior is valid also for plugins, I have to check them
> 
> I used a workaround to fix it (maybe not so pretty) I think you can change/extend it to handle your paid plugins too
> 
> ```
> add_filter( 'themes_api', function ( $res, $action, $args ) {
>       if ( $action == 'theme_information' ) {
> 	      if (  $args->slug == 'my_theme'  ) {
> 		      $res = true;
> 	      }
>       }
>       return $res;
> }, 3, 9999 );
> 
>     add_filter( 'themes_api_result', function ( $res, $action, $args ) {
>         if ( $action == 'theme_information' ) {
> 	      if (  $args->slug == 'my_theme'  ) {
> 		        return new WP_Error( "Disabled Theme API Result" );
> 	        }
>         }
>     
>         return $res;
>     }, 3, 9999 );
> ```

**Comment by kimdre** [comment]
Any news here? Is it possible to implement something to disable/ignore that error in wp-cli?

**Comment by octoxan** [comment]
This error is another thing on the long list of things wrong with Wordpress.

**Comment by schlessera** [comment]
Work is being done on getting the behavior of WP-CLI to properly align with what WordPress Core is doing. This is what the `--context=admin` flag is supposed to fix. There are still a few minor issues to work out, but we're moving towards all discrepancies between CLI and the admin dashboard when it comes to plugin updates to be eliminated.

**Comment by octoxan** [comment]
Awesome, that's good to hear. Thanks @schlessera!

**Comment by theDanielJLewis** [comment]
@infocube-dev-team, did you put that in your theme's functions.php, a single-purpose plugin, or somewhere else?

**Comment by kipmyk** [comment]
Hey all 👋, I run into this recently on my end. Is there any update on the same?

**Comment by kapn1966** [comment]
This was really causing me trouble, so I just created a bash scripted workaround. It could be adapted for other platforms I'm sure.
`for p in $(/usr/local/bin/wp plugin list  --update=available --field=name | xargs); do
        /usr/local/bin/wp plugin update
done`
You could also do something like `wp plugin list  --update=available --field=name | xargs wp plugin update` as a one-liner, but I'm working on an overall script to runn from cron, so a loop was a bit cleaner for me in that context.

**Comment by rhtenhove** [comment]
Using the oneliner with great success, thanks for the tip. Add `-r` right after `xargs` to prevent an error when there's nothing to update.

**Comment by schlessera** [comment]
Please, anyone in here, could you run a test to see if adding the `--context=auto` flag to your update command fixes the issue?

**Comment by ernilambar** [comment]
> Please, anyone in here, could you run a test to see if adding the `--context=auto` flag to your update command fixes the issue?

No. Adding `--context=auto` also gives same output.

**Comment by swissspidy** [comment]
If anyone has a plugin where you can still reproduce this with, please let us know so we can test it ourselves, otherwise I assume this has been resolved.

**Comment by RoundAboutWEB** [comment]
**Example Plugin: woo-essential**

<img width="1265" height="659" alt="Image" src="https://github.com/user-attachments/assets/1abd495d-958a-473e-9054-e265c1162449" />

**Comment by swissspidy** [comment]
Thanks! If you could provide me a ZIP of the plugin via Slack for testing, that would be helpful.

**Comment by RoundAboutWEB** [comment]
This plugin requires a paid license, so I don't want to make the ZIP file publicly available here. Is there another option?

**Comment by swissspidy** [comment]
Yes, share it privately via Slack DM :)

**Comment by RoundAboutWEB** [comment]
I sent you the file via Slack.

**Comment by swissspidy** [comment]
While I am currently unable to reproduce the "version higher than expected" for woo-essential with WP-CLI nightly, the experience is definitely much better with `--context=auto`:

```
$ wp plugin list
+---------------------------+----------+-----------+---------+----------------+-------------+
| name                      | status   | update    | version | update_version | auto_update |
+---------------------------+----------+-----------+---------+----------------+-------------+
| ai-provider-for-anthropic | active   | none      | 1.0.2   |                | off         |
| ai-provider-for-google    | active   | none      | 1.0.2   |                | off         |
| gutenberg                 | inactive | available | 22.2.0  | 22.6.0         | off         |
| hello                     | inactive | none      | 1.7.2   |                | off         |
| sample-plugin             | inactive | none      | 0.1.0   |                | off         |
| woocommerce               | active   | available | 10.5.2  | 10.5.3         | off         |
| woo-essential             | active   | none      | 4.0.0   |                | off         |
+---------------------------+----------+-----------+---------+----------------+-------------+

$ wp plugin list --context=auto
+---------------------------+----------+-----------+---------+----------------+-------------+
| name                      | status   | update    | version | update_version | auto_update |
+---------------------------+----------+-----------+---------+----------------+-------------+
| ai-provider-for-anthropic | active   | none      | 1.0.2   |                | off         |
| ai-provider-for-google    | active   | none      | 1.0.2   |                | off         |
| gutenberg                 | inactive | available | 22.2.0  | 22.6.0         | off         |
| hello                     | inactive | none      | 1.7.2   |                | off         |
| sample-plugin             | inactive | none      | 0.1.0   |                | off         |
| woocommerce               | active   | available | 10.5.2  | 10.5.3         | off         |
| woo-essential             | active   | available | 4.0.0   | 4.1.0          | off         |
+---------------------------+----------+-----------+---------+----------------+-------------+
```

**Comment by shaneonabike** [comment]
For the most part this seems to work but I have a weird situation with the [members](https://en-ca.wordpress.org/plugins/members/) when enabling redirect non-admins. It complains that is attempting to redirect. Is that because the context essentially is saying _be whatever user_ when attempting the upgrade?

Would there be a way to avoid the redirect error

```
Warning: Some code is trying to do a URL redirect. Backtrace:
#0 /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php(343): WP_CLI\Utils\wp_redirect_handler('...')
#1 /var/aegir/platforms/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters('...', Array)
#2 /var/aegir/platforms/wordpress/wp-includes/pluggable.php(1492): apply_filters('...', '...', 302)
#3 /var/aegir/platforms/wordpress/wp-content/plugins/members/addons/members-admin-access/app/functions-admin.php(30): wp_redirect('...')
#4 /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php(341): Members\AddOns\AdminAccess\access_check('')
#5 /var/aegir/platforms/wordpress/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters('', Array)
```

**Comment by swissspidy** [comment]
> For the most part this seems to work but I have a weird situation with the [members](https://en-ca.wordpress.org/plugins/members/) when enabling redirect non-admins. It complains that is attempting to redirect. Is that because the context essentially is saying _be whatever user_ when attempting the upgrade?

Not quite. The context makes it so that your plugins think they are in wp-admin instead of being accessed via CLI. And some plugins redirect you to some onboarding screen after activation.

> Would there be a way to avoid the redirect error

I'll have to think about that. Maybe we should hide these warnings in an admin context.

**Comment by designzwang** [comment]
@swissspidy  let me join in to this very old issue. I use quite a lot paid plugins on different sites i manage with wp-cli, and over time I have seen the "higher than expected" warning regularly here and there. However it seems ephemeral and not always reproducible. 

Currently, I only  see it with the paid version of Kadence. But take a look at the following comparison:

`
Site A: ------------------
php -v && wp core version && wp cli version &&  wp plugin list --all | grep kade  && wp plugin update --all
PHP 8.3.31 (cli) (built: May 19 2026 23:11:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.31, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.31, Copyright (c), by Zend Technologies
7.0
WP-CLI 2.12.0
kadence-blocks-pro      active  version higher than expected    2.8.17          off
kadence-blocks  active  none    3.7.6           off
Warning: kadence-blocks-pro: version higher than expected.
Error: No plugins updated.

Site B: ------------------
php -v && wp core version && wp cli version &&  wp plugin list --all | grep kade
PHP 8.3.31 (cli) (built: Jun 24 2026 01:29:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.31, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.31, Copyright (c), by Zend Technologies
7.0
WP-CLI 2.12.0
kadence-blocks-pro      active  available       2.8.16  2.8.17  off
kadence-blocks  active  none    3.7.6           off

`
Site A is essentially a dev clone of Site B that is running the same code  and plugins from the same repo using the same docker image. They diverge a little bit depending on when they are rebuild and deployed and may have diverging ENV vars, but in general they are identical. So the "version higher" appearing only on one site is strange.
Since using Kadence Pro is tied to a license, I think it wouldn't help to send you a zip.  If you have any idea where to look further, let me know. 

So far BTW  this has not caused real problems or errors, it's just something i had to factor in when doing automated admin tasks, and I guess it triggers many wpcli users to google the error message.

Regards
Uli

(Edit:  adding --context=auto does not change the warning/error message )

**Comment by swissspidy** [comment]
Can you update to WP-CLI nightly and try again?

**Comment by designzwang** [comment]
Hi @swissspidy  I did so in my clone environment with WP-CLI 2.13.0-alpha-4c7cbf8 . 
Result: Now we have an additional warning  ;-)  


```
php -v && swp core version && swp cli version &&  swp plugin list --all --context=auto | grep kadence 
PHP 8.3.31 (cli) (built: May 19 2026 23:11:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.31, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.31, Copyright (c), by Zend Technologies
7.0
WP-CLI 2.13.0-alpha-4c7cbf8
Warning: The mcp-adapter serve command is registering an argument --user that conflicts with a global argument of the same name.
kadence-blocks-pro      active  version higher than expected    2.8.17          off
kadence-blocks  active  none    3.7.6           off
```

Comments: "swp" is just a sudo alias to wp, no difference with or without --context=auto, and Kadence Pro 2.8.17 is in fact the current/latest version that is already present. Kadence Pro, btw,  belongs to the plugins where command line upgrades with wpcli work - this is not true for some paid plugins or themes.

**Comment by schlessera** [comment]
Thanks for the detailed comparison, @designzwang !

For reference, Kadence Blocks 3.7.6 introduced Harbor-backed updates for premium legacy licenses. Harbor can write an older or empty `new_version` into the `update_plugins` transient's `no_update` section. WP-CLI currently interprets either as `version higher than expected`, while WordPress treats every entry in `no_update` as up to date.

This fits the difference between the two sites and explains why `--context=auto` does not change the result. I now have deterministic reproductions for both cases, without requiring access to a paid plugin.
