### ISSUE TITLE
Heads-up: wp-cli not compatible with PHP 8.0

### ISSUE THREAD

**Issue by ottok** [wp-cli/wp-cli#5452]
I started testing PHP 8.0 with WordPress today, and noticed wp-cli has a dependency that is used in many commands and which is not compatible with PHP 8.0. See https://github.com/rmccue/Requests/issues/391#issuecomment-706784645

**Comment by jrfnl** [comment]
To qualify that statement: that dependency was actually made compatible over a year ago. There just hasn't been a new tagged release since.

**Comment by ottok** [comment]
I was about to send a PR about Travis-CI improvements in this field, but there are odd composer dependency installation errors. Nevertheless, the changes I propose is https://github.com/wp-cli/wp-cli/compare/master...ottok:php8.0

**Comment by ottok** [comment]
WordPress core is far from PHP 8.0 compatible yet, so I guess this isn't that urgent?
See https://make.wordpress.org/hosting/test-results/r49129/seravobot-r49129/

**Comment by jrfnl** [comment]
@ottok I'm fully aware of that, probably more so than some...

The failures you are seeing on the page you linked are wrong though and unrelated to WP itself.
The tests on WP `trunk` will pass given the right setup (Docker with `composer install`, not using the PHPUnit Phar).

All the same WP only has +/- 15% code coverage with tests, so the tests passing actually doesn't mean anything.

**Comment by jrfnl** [comment]
Re: Travis - try using `WP_VERSION=master`. AFAIK, `latest` is the last tagged release (WP 5.5.) which is definitely not compatible, while `master` is current `trunk` which contains a lot of fixes already.

**Comment by schlessera** [comment]
I've pinged @rmccue to see if we can get a new tagged release of the Requests library. If not, we can lock to a newer commit that is known to be working. But I'd like to avoid that, so let's wait for Ryan's response for now.

**Comment by strarsis** [comment]
Lots of errors from different plugins when using the WP CLI:
````
Fatal error: Uncaught Error: Class "WP_CLI" not found
````

**Comment by tammullen** [comment]
Just adding as an example I get a Fatal error when using the `wp core update` command with PHP 8.0

When running
`$ wp core update --version=trunk` on PHP 7.4
I get this warning
```Warning: Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///usr/local/bin/wp-cli/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 30```

When running the same command
`$ wp core update --version=trunk` on PHP 8.0
I get the Fatal Error
```Fatal error: Declaration of WP_CLI\Core\CoreUpgrader::download_package($package, $check_signatures = true) must be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = []) in phar:///usr/local/bin/wp-cli/vendor/wp-cli/core-command/src/WP_CLI/Core/CoreUpgrader.php on line 30```

**Comment by ErvinSabic** [comment]
Hey guys, 

Just found out its not compatible as well. This is the error I'm getting. 

```
wp core update
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php:75
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php(75): implode()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php(36): WP_CLI\DocParser->get_longdesc()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(122): WP_CLI\Dispatcher\CompositeCommand->__construct()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(53): WP_CLI\Dispatcher\CommandFactory::create_composite_command()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/class-wp-cli.php(522): WP_CLI\Dispatcher\CommandFactory::create()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/cache-command/cache-command.php(12): WP_CLI::add_command()
#6 phar:///usr/local/bin/wp/vendor/composer/autoload_real.php(66): require('...')
#7 phar:///usr/local/bin/wp/vendor/composer/autoload_real.php(56): composerRequired174b00ead0ecd32acfb2802d835253a()
#8 phar:///usr/local/bin/wp/vendor/autoload.php(7): ComposerAutoloaderInitd174b00ead0ecd32acfb2802d835253a::getLoader()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/AutoloaderStep.php(49): require('...')
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\AutoloaderStep->process()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#12 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#13 /usr/local/bin/wp(4): include('...')
#14 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/DocParser.php on line 75
```

**Comment by anithegregorian** [comment]
This happens during search & replace:

```
PHP Fatal error:  Uncaught TypeError: unserialize(): Argument #1 ($data) must be of type string, array given in phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php:86
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php(86): unserialize(Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php(88): WP_CLI\SearchReplacer->run_recursively(Array, true, 1)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php(57): WP_CLI\SearchReplacer->run_recursively('a:24:{s:32:"2cc...', false)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/Search_Replace_Command.php(554): WP_CLI\SearchReplacer->run('a:24:{s:32:"2cc...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/Search_Replace_Command.php(390): Search_Replace_Command->php_handle_col('option_value', Array, 'wp_options', 'https://satsolu...', 'http://localhos...')
#5 [internal function]: Search_Replace_Command->__invoke(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1160): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#15 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#16 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#17 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/search-replace-command/src/WP_CLI/SearchReplacer.php on line 86
```

**Comment by ottok** [comment]
I am unable to reproduce this.

```
DEVELOPMENT [@wordpress:~] $ php -v
PHP 8.0.0RC3 (cli) (built: Oct 31 2020 17:06:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0RC3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.0beta1, Copyright (c) 2002-2020, by Derick Rethans

DEVELOPMENT [@wordpress:~] $ wp search-replace https://wordpress.local https://wordpress.localhost
+------------------+-----------------------+--------------+------+
| Table            | Column                | Replacements | Type |
+------------------+-----------------------+--------------+------+
| wp_commentmeta   | meta_key              | 0            | SQL  |
| wp_commentmeta   | meta_value            | 0            | SQL  |
| wp_comments      | comment_author        | 0            | SQL  |
| wp_comments      | comment_author_email  | 0            | SQL  |
| wp_comments      | comment_author_url    | 0            | SQL  |
| wp_comments      | comment_author_IP     | 0            | SQL  |
...
Success: Made 6 replacements. Please remember to flush your persistent object cache with `wp cache flush`.
```

**Comment by gadelkareem** [comment]
I am also getting errors using wp-cli 2.4.0 with PHP 8
```
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/public_html/web/wp-content/plugins/jetpack/modules/shortcodes.php on line 94
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /home/public_html/web/wp-content/plugins/jetpack/modules/shortcodes.php on line 94
```

**Comment by ottok** [comment]
> PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/public_html/web/wp-content/plugins/jetpack/modules/shortcodes.php on line 94
> Fatal error: Array and string offset access syntax with curly braces is no longer supported in /home/public_html/web/wp-content/plugins/jetpack/modules/shortcodes.php on line 94

Run `rm -rf /home/public_html/web/wp-content/plugins/jetpack/` and try again ;)

**Comment by gadelkareem** [comment]
Jetpack is currently used by wordpress

**Comment by chesio** [comment]
> Jetpack is currently used by wordpress

And it is causing the fatal error you have posted - you should report it by Jetpack, it's not WP-CLI related.

**Comment by barrychapman** [comment]
I am getting a mix of these same errors:

```
Fatal error: Uncaught Error: Class "WP_CLI" not found in /var/www/vhosts/buyterpenesonline.com/wp-content/plugins/woocommerce-product-feeds/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler.php:168
Stack trace:
#0 /var/www/vhosts/buyterpenesonline.com/wp-content/plugins/woocommerce-product-feeds/vendor/woocommerce/action-scheduler/action-scheduler.php(44): ActionScheduler::init()
#1 /var/www/vhosts/buyterpenesonline.com/wp-content/plugins/woocommerce-customer-order-csv-export/vendor/woocommerce/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_3_dot_1_dot_6()
#2 /var/www/vhosts/buyterpenesonline.com/wp-includes/class-wp-hook.php(290): ActionScheduler_Versions::initialize_latest_version()
#3 /var/www/vhosts/buyterpenesonline.com/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#4 /var/www/vhosts/buyterpenesonline.com/wp-includes/plugin.php(484): WP_Hook->do_action()
#5 /var/www/vhosts/buyterpenesonline.com/wp-settings.php(423): do_action()
#6 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('...')
#7 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#8 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#9 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#10 phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#11 phar:///usr/bin/wp/php/boot-phar.php(11): include('...')
#12 /usr/bin/wp(4): include('...')
#13 {main}
  thrown in /var/www/vhosts/buyterpenesonline.com/wp-content/plugins/woocommerce-product-feeds/vendor/woocommerce/action-scheduler/classes/abstracts/ActionScheduler.php on line 168
Error: There has been a critical error on this website.Learn more about troubleshooting WordPress. There has been a critical error on this website.
```

**Comment by sparkbold** [comment]
This issue is closed with the most recent update of WP-CLI version 2.6

**Comment by parwaizjan** [comment]
Hi. I get those deprecated errors. This is what I get when I type wp --info

OS:	Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/8.1.8/bin/php
PHP version:	8.1.8
php.ini used:	/usr/local/etc/php/8.1/php.ini
MySQL binary:	/usr/local/opt/mysql@5.7/bin/mysql
MySQL version:	mysql  Ver 14.14 Distrib 5.7.38, for osx10.17 (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/parwaizjan/Sites
WP-CLI packages dir:	/Users/parwaizjan/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.6.0

Any ideas? 

Thanks!
