### ISSUE TITLE
[PHP 8] Using undefined constants is now a fatal error.

### ISSUE THREAD

**Issue by TimothyBJacobs** [wp-cli/wp-cli#5473]
There are a couple tests that use an undefined constant and look for the undefined constant warning in standard error. On PHP 8 these now cause fatal errors instead of warnings, causing the tests to fail. For example:

```
wp eval 'echo CONST_WITHOUT_QUOTES;'

    PHP Fatal error:  Uncaught Error: Undefined constant "CONST_WITHOUT_QUOTES" in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code:1
    Stack trace:
    #0 vendor/wp-cli/eval-command/src/Eval_Command.php(37): eval()
    #1 [internal function]: Eval_Command->__invoke(Array, Array)
    #2 php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
    #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
    #4 php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func(Object(Closure), Array, Array)
    #5 php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
    #6 php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command(Array, Array)
    #7 php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
    #8 php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke('before_wp_load')
    #9 php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #10 php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #11 php/wp-cli.php(27): WP_CLI\bootstrap()
    #12 php/boot-fs.php(17): require_once('/Users/timothyb...')
    #13 {main}
      thrown in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
    Fatal error: Uncaught Error: Undefined constant "CONST_WITHOUT_QUOTES" in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code:1
    Stack trace:
    #0 vendor/wp-cli/eval-command/src/Eval_Command.php(37): eval()
    #1 [internal function]: Eval_Command->__invoke(Array, Array)
    #2 php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
    #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
    #4 php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func(Object(Closure), Array, Array)
    #5 php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
    #6 php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command(Array, Array)
    #7 php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
    #8 php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke('before_wp_load')
    #9 php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #10 php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #11 php/wp-cli.php(27): WP_CLI\bootstrap()
    #12 php/boot-fs.php(17): require_once('/Users/timothyb...')
    #13 {main}
      thrown in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
    Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
    cwd: /var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-flags.feature.61-5fac294c5a3947.34272270/
    run time: 0.26895189285278
    exit status: 1
    In step `Then STDOUT should be:'.                                                                                             # vendor/wp-cli/wp-cli-tests/features/steps/then.php:21
    From scenario `Debug run'.                                                                                                    # features/flags.feature:61
    Of feature `Global flags'.
```

For this it seems like it might be better to just call `trigger_error()` instead of trying to generate a PHP warning thru usage of invalid code?

```
$ wp eval "echo 'TEST_CONFIG_OVERRIDE => ' . TEST_CONFIG_OVERRIDE;"

    PHP Fatal error:  Uncaught Error: Undefined constant "TEST_CONFIG_OVERRIDE" in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code:1
    Stack trace:
    #0 vendor/wp-cli/eval-command/src/Eval_Command.php(37): eval()
    #1 [internal function]: Eval_Command->__invoke(Array, Array)
    #2 php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
    #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
    #4 php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func(Object(Closure), Array, Array)
    #5 php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
    #6 php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command(Array, Array)
    #7 php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
    #8 php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke('before_wp_load')
    #9 php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #10 php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #11 php/wp-cli.php(27): WP_CLI\bootstrap()
    #12 php/boot-fs.php(17): require_once('/Users/timothyb...')
    #13 {main}
      thrown in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
    Fatal error: Uncaught Error: Undefined constant "TEST_CONFIG_OVERRIDE" in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code:1
    Stack trace:
    #0 vendor/wp-cli/eval-command/src/Eval_Command.php(37): eval()
    #1 [internal function]: Eval_Command->__invoke(Array, Array)
    #2 php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
    #3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
    #4 php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func(Object(Closure), Array, Array)
    #5 php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
    #6 php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command(Array, Array)
    #7 php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
    #8 php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke('before_wp_load')
    #9 php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
    #10 php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
    #11 php/wp-cli.php(27): WP_CLI\bootstrap()
    #12 php/boot-fs.php(17): require_once('/Users/timothyb...')
    #13 {main}
      thrown in vendor/wp-cli/eval-command/src/Eval_Command.php(37) : eval()'d code on line 1
    Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
    cwd: /var/folders/7d/mcmynw4x60v3y8nwlfz3ppg80000gn/T/wp-cli-test-run-wp-config.feature.3-5fac29ee5c5131.28511182/
    run time: 0.27620100975037
    exit status: 1
    In step `Then STDOUT should contain:'.                                                                                        # vendor/wp-cli/wp-cli-tests/features/steps/then.php:21
    From scenario `Default WordPress install with WP_CONFIG_PATH specified in environment variable'.                              # features/wp-config.feature:3
    Of feature `wp-config'.
```

This seems like it could be fixed by making this eval something like `echo defined( 'TEST_CONFIG_OVERRIDE' ) ? TEST_CONFIG_OVERRIDE : 'missing'`. And then look for either `missing` or `success`.

**Comment by schlessera** [comment]
This was resolved.
