### ISSUE TITLE
PHP8.0-FPM fastcgi ubuntu 20.

### ISSUE THREAD

**Issue by MaxSmile** [wp-cli/wp-cli#5509]
**Firstly the environment (release 2.4.0 gives the same, updated to nightly with the hope it will work there):**
wp --info
OS:	Linux 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.3
php.ini used:	/etc/php/8.0/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/swellsyme.com
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.5.0-alpha-3f4c34b

**The error:**

sudo -u www-data -- wp core download
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(775): Requests::request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(310): WP_CLI\Utils\http_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(319): Core_Command::read()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/core-command/src/Core_Command.php(183): Core_Command->get_download_offer()
#6 [internal function]: Core_Command->download()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(99): call_user_func()
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195

**Comment by MaxSmile** [comment]
**Update gives the same:**

wp cli update
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(775): Requests::request()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php(403): WP_CLI\Utils\http_request()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php(310): CLI_Command->get_updates()
#5 [internal function]: CLI_Command->update()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(99): call_user_func()
#7 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(489): call_user_func()
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(380): WP_CLI\Dispatcher\Subcommand->invoke()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(403): WP_CLI\Runner->run_command()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(87): WP_CLI\Runner->run_command_and_exit()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1116): WP_CLI\Runner->do_early_invoke()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#16 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#17 /usr/local/bin/wp(4): include('...')
#18 {main}
  thrown in phar:///usr/local/bin/wp/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
