### ISSUE TITLE
Fatal Error on all commands

### ISSUE THREAD

**Issue by nathanmerry** [wp-cli/wp-cli#5536]
## Bug Report

**Describe the current, buggy behavior**

A couple of days ago my WP cli commands stopped working. I am not sure why it has stopped suddenly.

Now whenever I run any sort of WP CLI command I get the following error:

```
Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php:259
Stack trace:
#0 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php(259): preg_match('#^@[A-Za-z0-9-_...', Array)
#1 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(950): WP_CLI\Configurator->merge_yml('/Users/nathanme...', NULL)
#2 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/ConfigureRunner.php(23): WP_CLI\Runner->init_config()
#3 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\ConfigureRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/boot-fs.php(17): require_once('/Users/nathanme...')
#6 {main}
  thrown in /Users/nathanmery/.composer/vendor/wp-cli/wp-cli/php/WP_CLI/Configurator.php on line 259

```
I am on a Mac version 10.14.6, using bash.

I initially installed it using CURL, but then tried to install it using composer and still am getting the same error.

Would really appreciate some advice here 🙏

**Comment by nathanmerry** [comment]
All good, was a problem with my config file
