### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "MYSQLI_CLIENT_SSL"

### ISSUE THREAD

**Issue by agitnaeta** [wp-cli/wp-cli#5555]
I try to run the wp CLI uninstall the plugin 

`wp plugin uninstall plugin-name`

After that, I receive an error that said 

`PHP Fatal error:  Uncaught Error: Undefined constant "MYSQLI_CLIENT_SSL" in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code:43
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231): eval()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1192): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(77): WP_CLI\Bootstrap\LaunchRunner->process()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('...')
#6 /usr/local/bin/wp(4): include('...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1231) : eval()'d code on line 43`
  
  i try using this on config 
`define('DB_SSL', true);`
`define( 'MYSQL_SSL_CA', '/path-to-certificate');`
`define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL | MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT );`

really appreciate for help :)

**Comment by agitnaeta** [comment]
Sorry the issue was because i do not install `php-mysql` on server
