### ISSUE TITLE
Running wp command show Fatal error

### ISSUE THREAD

**Issue by kozicpetar** [wp-cli/wp-cli#5631]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I have installed wp-cli on WHM servers. All Cpanel users can use it. With latest version I have problem and I get strange error message when I run `wp` command.

I tried to reinstall wp-cli, I checked disabled functions in php and I tried with different versions of PHP (7.4 and 8.0) but without success.

I get error about `proc_close()`

**Describe how other contributors can replicate this bug**

- run `wp` command
- get error:
``` 
Fatal error: Uncaught TypeError: proc_close(): Argument #1 ($process) must be of type resource, bool given in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/Help_Command.php:143
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/Help_Command.php(143): proc_close(false)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/Help_Command.php(94): Help_Command::pass_through_pager('\e[1mNAME\e[0m\n\n ...')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/Help_Command.php(31): Help_Command::show_help(Object(WP_CLI\Dispatcher\RootCommand))
#3 [internal function]: Help_Command->__invoke(Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func(Array, Array, Array)
#5 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(491): call_user_func(Object(Closure), Array, Array)
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(417): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(440): WP_CLI\Runner->run_command(Array, Array)
#9 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): WP_CLI\Runner->run_command_and_exit()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#11 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#13 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#14 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#15 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/Help_Command.php on line 143
``` 

**Describe what you expect as the correct outcome**

I expect to get help information when I running `wp` command without errors.

**Let us know what environment you are running this on**

```
OS:	Linux 3.10.0-962.3.2.lve1.5.39.el7.x86_64 #1 SMP Thu Sep 17 06:10:33 EDT 2020 x86_64
Shell:	/bin/bash
PHP binary:	/opt/cpanel/ea-php80/root/usr/bin/php.cagefs
PHP version:	8.0.16
php.ini used:	/opt/cpanel/ea-php80/root/etc/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)
SQL modes:
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/username/public_html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.6.0
``` 

**Provide a possible solution**

**Provide additional context/screenshots**

- Running command `wp --version` get right output:
`WP-CLI 2.6.0`

- Running command `wp --info` also works.

- Running command `wp plugin list` also works.

**Comment by danielbachhuber** [comment]
Thanks for the report, @kozicpetar !

Were you able to track down the root cause?

**Comment by danielbachhuber** [comment]
Feel free to re-open the issue if you track down more details.
