### ISSUE TITLE
Problem installing Wp cli preg_match error

### ISSUE THREAD

**Issue by leoarayas** [wp-cli/wp-cli#5640]
Hi guys!

Sorry to botther you. I have tried everything to make work wp cli. 

I have a Mojave osx with hombrew.

I had install httpd and php 7.4 and php 8 and changing the php version and reinstalling httpd and everything in my hand, i haven't found a solution.

When I execute the first command i have the next error.

```
 php wp-cli.phar --info
PHP Warning:  preg_match() expects parameter 2 to be string, array given in phar:///Users/leo.arayas/Sites/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1058

Warning: preg_match() expects parameter 2 to be string, array given in phar:///Users/leo.arayas/Sites/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1058
PHP Warning:  preg_match() expects parameter 2 to be string, array given in phar:///Users/leo.arayas/Sites/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1073

Warning: preg_match() expects parameter 2 to be string, array given in phar:///Users/leo.arayas/Sites/wp-cli.phar/vendor/wp-cli/wp-cli/php/utils.php on line 1073
```
Hoping if somebody have a solution
Thanks

**Comment by leoarayas** [comment]
Hi @danielbachhuber , i had a big problem with php conflict using homebrew because i haved installed php before using osx terminal

Now i have this error but i think that the error is with php 8

```
HP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1058
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1058): preg_match('#^((docker|dock...', Array, NULL)
#1 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(466): WP_CLI\Utils\parse_ssh_url(Array)
#2 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1146): WP_CLI\Runner->run_ssh_command(Array)
#3 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
```

**Comment by danielbachhuber** [comment]
@leoarayas From the error message, it seems like there's an array of data defined for the `--ssh=<ssh>` parameter.

Can you share the command you're running? Also, can you share the output of `wp cli info` ?

**Comment by leoarayas** [comment]
```
leo.arayas@Leo ~ % wp
PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1058
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1058): preg_match('#^((docker|dock...', Array, NULL)
#1 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(466): WP_CLI\Utils\parse_ssh_url(Array)
#2 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1146): WP_CLI\Runner->run_ssh_command(Array)
#3 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/Cellar/wp-cli/2.6.0/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1058

Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1058
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1058): preg_match('#^((docker|dock...', Array, NULL)
#1 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(466): WP_CLI\Utils\parse_ssh_url(Array)
#2 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1146): WP_CLI\Runner->run_ssh_command(Array)
#3 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/Cellar/wp-cli/2.6.0/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1058
```

```
leo.arayas@Leo ~ % wp cli info 
PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1058
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1058): preg_match('#^((docker|dock...', Array, NULL)
#1 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(466): WP_CLI\Utils\parse_ssh_url(Array)
#2 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1146): WP_CLI\Runner->run_ssh_command(Array)
#3 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/Cellar/wp-cli/2.6.0/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1058

Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php:1058
Stack trace:
#0 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php(1058): preg_match('#^((docker|dock...', Array, NULL)
#1 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(466): WP_CLI\Utils\parse_ssh_url(Array)
#2 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1146): WP_CLI\Runner->run_ssh_command(Array)
#3 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/Cellar/wp-cli/2.6.0/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/Cellar/wp-cli/2.6.0/bin/wp/vendor/wp-cli/wp-cli/php/utils.php on line 1058
```

i Attach a list of brew installs

![Captura de Pantalla 2022-07-22 a la(s) 12 00 05](https://user-images.githubusercontent.com/105768882/180478511-34d66a5b-f307-42b0-b44b-489f213fedb7.jpg)

**Comment by danielbachhuber** [comment]
@leoarayas Do you have a file at `~/.wp-cli/config.yml` ? If so, can you share its contents?

**Comment by leoarayas** [comment]
Thanks Daniel! I was finally able to fix it!!!! I remove everything en config.yml and now its working. Sorry for all the trouble, but i dont remember anything about this file. I close the issue because now its working.

**Comment by danielbachhuber** [comment]
💯 Glad you were able to figure it out.
