### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function add_action() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1309) : eval()'d code:11

### ISSUE THREAD

**Issue by mu7mdmagdy** [wp-cli/wp-cli#5814]
Fatal error: Uncaught Error: Call to undefined function add_action() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1309) : eval()'d code:11
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1309): eval()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1267): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1309) : eval()'d code on line 11

**Comment by swissspidy** [comment]
Hi there

Would you mind sharing the steps that you took that lead to this fatal error?

Please note that you should have seen an option to fill out a bug report template when you created a new issue. It would be tremendously helpful if you would fill out this template for us.

Here is the template, please copy & paste it and fill it out in a new comment:

```
## Bug Report

<!--- ⚠️ Before you start reporting the bug... ---

**Is your bug report directly related to a specific command?**

If yes, make sure you create the issue in the correct repository.

Here's a quick overview to where each command lives:

* `wp (cache|transient) *` https://github.com/wp-cli/cache-command
* `wp checksum` https://github.com/wp-cli/checksum-command
* `wp config *` https://github.com/wp-cli/config-command
* `wp core *` https://github.com/wp-cli/core-command
* `wp cron *` https://github.com/wp-cli/cron-command
* `wp db *` https://github.com/wp-cli/db-command
* `wp embed *` https://github.com/wp-cli/embed-command
* `wp (eval|eval-file)` https://github.com/wp-cli/eval-command
* `wp export` https://github.com/wp-cli/export-command
* `wp (option|post|comment|user|term|site) *` https://github.com/wp-cli/entity-command
* `wp i18n` https://github.com/wp-cli/i18n-command
* `wp import` https://github.com/wp-cli/import-command
* `wp language` https://github.com/wp-cli/language-command
* `wp maintenance-mode *` https://github.com/wp-cli/maintenance-mode-command
* `wp media *` https://github.com/wp-cli/media-command
* `wp package *` https://github.com/wp-cli/package-command
* `wp (plugin|theme) *` https://github.com/wp-cli/extension-command
* `wp rewrite` https://github.com/wp-cli/rewrite-command
* `wp (role|cap) *` https://github.com/wp-cli/role-command
* `wp scaffold *` https://github.com/wp-cli/scaffold-command
* `wp search-replace` https://github.com/wp-cli/search-replace-command
* `wp server` https://github.com/wp-cli/server-command
* `wp shell` https://github.com/wp-cli/shell-command
* `wp super-admin *` https://github.com/wp-cli/super-admin-command
* `wp (widget|sidebar) *` https://github.com/wp-cli/widget-command

If you are not in the correct repository, you can just close this issue/window without submitting and navigate to the correct one.

**Are you unsure about which repository to post the bug report into?**

Just head over to the [`wp-cli/wp-cli`](https://github.com/wp-cli/wp-cli) repository and [create a new issue in that repository](https://github.com/wp-cli/wp-cli/issues/new). The maintainers can still move the bug report into the correct repository later on.

--- ✅ If you are in the correct location now... --->

- [ ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

A clear and concise description of the behavior that produces an incorrect result or error.

Remember: more information is better. Please provide context on how you're running the command to make sure we're all on the same page when reasoning about this.

**Describe how other contributors can replicate this bug**

- a list of
- steps to replicate
- the error condition

```js
// You can also use code snippets if needed.
```

**Describe what you expect as the correct outcome**

A clear and concise description of what you expected to happen (or code).

**Let us know what environment you are running this on**

```
(Paste the output of "wp cli info" into this box)
```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/screenshots**

Add any other context about the problem here.

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).
```

**Comment by chriscroome** [comment]
I have this error on a WordPress / CiviCRM site with the latest WP-CLI:

```bash
wp cli info
OS:	Linux 6.1.0-50-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.176-1 (2026-07-02) x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.3
PHP version:	8.3.32
PHP memory limit:	-1
php.ini used:	/etc/php/8.3/cli/php.ini
MySQL binary:	/usr/bin/mariadb
MySQL version:	mariadb  Ver 15.1 Distrib 10.11.14-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	phar:///usr/local/bin/wp
WP-CLI packages dir:	/home/example/.wp-cli/packages/
WP-CLI cache dir:	/home/example/.wp-cli/cache
WP-CLI global config:	/home/example/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	2.13.0-alpha-dc63cdc
```

It is easy to trigger:

```bash
wp option get home
PHP Fatal error:  Uncaught Error: Call to undefined function add_action() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060) : eval()'d code:120
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060): eval()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2019): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(31): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(88): WP_CLI\Bootstrap\LaunchRunner->process()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(35): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#6 /usr/local/bin/wp(4): include('...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060) : eval()'d code on line 120
```

The `/home/example/.wp-cli/config.yml` contents:

```yaml
---
apache_modules:
  - mod_rewrite
...
```

I have the same error with PHP 8.4, some commands work:

```bash
wp core verify-checksums 
Success: WordPress installation verifies against checksums.
```

But others don't:

```bash
wp core check-update
PHP Fatal error:  Uncaught Error: Call to undefined function add_action() in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060) : eval()'d code:120
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060): eval()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2019): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(31): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(88): WP_CLI\Bootstrap\LaunchRunner->process()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(35): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#6 /usr/local/bin/wp(4): include('...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060) : eval()'d code on line 120
```
```

**Comment by swissspidy** [comment]
> `thrown in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(2060) : eval()'d code on line 120`

This is that line:

https://github.com/wp-cli/wp-cli/blob/1c06435200bcaeafd493d9492340309885e565fb/php/WP_CLI/Runner.php#L2060

There, WP-CLI basically loads your entire `wp-config.php` file (up until the `wp-settings.php` inclusion part). So your config file might be containing a call to `add_action()`. Could you perhaps share the config file here (with credentials redacted of course) to confirm?
